env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    - XDEBUG_MODE=coverage


language: php
php:
  - '7.4'
  - '8.0'

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build  -t clover --exit-code $TRAVIS_TEST_RESULT; fi